#!/bin/bash
str1='0.0028'
str2='1000000'
sed -i "s/disdis=${str1}/disdis=${str2}/" mean1.py
sed -i "s/disdis=${str1}/disdis=${str2}/" mean2.py
sed -i "s/disdis=${str1}/disdis=${str2}/" mean3.py
sed -i "s/disdis=${str1}/disdis=${str2}/" mean_overtone1.py
sed -i "s/disdis=${str1}/disdis=${str2}/" mean_overtone2.py
sed -i "s/disdis=${str1}/disdis=${str2}/" mean_overtone3.py

sbatch sub_mean_overtone1.sh
sbatch sub_mean_overtone2.sh
sbatch sub_mean_overtone3.sh

sbatch sub_mean1.sh
sbatch sub_mean2.sh
sbatch sub_mean3.sh
