name: ringdown
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - h5py
  - arviz
  - matplotlib
  - pandas
  - pymc
  - scipy
  - lalsuite
  - qnm
  - seaborn
  - python=3
  - jupyterlab
